package Recursos;

public class RdP {

    /*
     OPCION 1: MODELAR QUE T0 NO EXISTE Y QUE LOS HILOS 1 Y 2 DIRECTAMENTE CREAN LA IMAGEN, COMO SI LA ESTUVIERAN
     SACANDO DE P0 (TOTAL LOS IT LARGAN DESDE T1 O T2)

     OPCION 2: MODELAR QUE UN HILO GENERA IMAGENES AL AZAR A UNA VELOCIDAD NO MUY DESCOMUNAL Y LA PONE EN UN
     BUFFER IDDLE, ESTO MODELARLO PARA QUE NO SE TENGA EN CUENTA EN LOS IT, Y QUE T1 Y T2 SAQUE LAS IMAGENES DEL
     BUFFER IDDLE
     */


}
